codemagic

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,28 +1,26 @@
-# FCI_BUILD_DIR is a predefined environment variable pointing to the root of the Flutter project
-cd $FCI_BUILD_DIR
 
-# Go to the android folder which contains the "gradlew" script used
-# for building Android apps from the terminal
-pushd android
-# Build an Android test APK (that's why we've created the MainActivityTest.java)
-./gradlew app:assembleAndroidTest
-# Build a debug APK, passing in the integration test file
-./gradlew app:assembleDebug -Ptarget="$FCI_BUILD_DIR/integration_test/app_test.dart"
-# Go back to the root of the project
-popd
+workflows:
+  my-workflow:
+    scripts:
+      - name: Launch emulator
+        script: |
+          set -e # exit on first failed command
+          cd $ANDROID_HOME/tools
+          emulator -avd emulator &
+          adb wait-for-device
+    
+        script: |
+          set -e # exit on first failed command
+          echo ${GCODE_base64?} > ./gcloud_key_file.json
+          gcloud auth activate-service-account --key-file=gcloud_key_file.json
+          gcloud --quiet config set project ${FIREBASE_PROJECT}
+      
+        script: |
+          set -e # exit on first failed command
 
-# Write the environment variable in base64 into a JSON file
-echo $GCODE_base64 | base64 --decode > ./gcloud_key_file.json
+          gcloud firebase test --help
+        
+        script: ./gradlew test
+        test_report: app/build/**/*.xml
 
-# Using the gcloud CLI (preinstalled on Codemagic) authenticate using the service account key
-gcloud auth activate-service-account --key-file=gcloud_key_file.json
-
-# Select YOUR Firebase project through which want to run the tests
-gcloud --quiet config set project sampletestprojectflutter
-
-# Run the Flutter integration tests as if they were regular Android instrumentation tests
-gcloud firebase test android run \
-  --type instrumentation \
-  --app build/app/outputs/apk/debug/app-debug.apk \
-  --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
-  --timeout 2m
+  
